
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /data
  ports:
    - 9000:9000
    - 9090:9090
  environment:
    MINIO_ROOT_USER: 'minioadmin'
    MINIO_ROOT_PASSWORD: 'minioadmin'
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

name: data-lakehouse
services:
  minio:
    <<: *minio-common
    volumes:
      - minio_data:/data

volumes:
  minio_data:
