name: resolv-pipelines
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - pip
  - pip:
      - apache-beam==2.55.*
      - tensorflow==2.16.*
      - matplotlib
      - git+ssh://git@github.com/resolv-libs/resolv-data.git@main
      - git+ssh://git@github.com/resolv-libs/resolv-mir.git@main
      - git+ssh://git@github.com/resolv-libs/resolv-ml.git@main
