name: data-execution-cluster
services:
  flink-jobmanager:
    image: flink:1.16.3-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager:
    image: flink:1.16.3-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    ports:
      - "8100-8200:8100-8200"
    scale: 1
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
      BEAM_WORKER_POOL_IN_DOCKER_VM: 1
      DOCKER_MAC_CONTAINER: 1

  python-worker-harness:
    image: python_3.11:mir
    build:
      context: .
      dockerfile: ./infrastructure/executor/sdk-harness/Dockerfile
    depends_on:
      - flink-jobmanager
    command: --worker_pool
    ports:
      - "50000:50000"